### ISSUE TITLE
Technical operability (Makefile, scripts sh, virtualenv and readme)

### ISSUE THREAD

**Issue by miltminz** [pyronear/pyro-risks#11]
Hello,
I think we need to package a bit better our project and document the installation process and how to use it.
Here is a suggestion of what it should be done in my opinion to improve the usability of pyronear-datascience.

- [ ] Scripts `activate.sh`, `init.sh`, `install.sh` for initialisation and activation of a virtualenv (conda env or pip3 venv) associated with the project
- [ ] `Makefile` for executing pipelines, tests, coverage, doc, installation etc.
- [x] `Readme` describing what an initial user should do technically to use our code. This will be then extended in the future to explain the content of the package
- [x] Assure that the package builds on different OS (Mac, Linux, Windows) (#15)

I can start working on this, I would like to discuss with you if you're ok with that and I'm happy to hear if you have different opinions or strategies.

**Comment by frgfm** [comment]
Hey there :wave: 

Regarding scripts and makefiles, I would say that I use them only for projects that require compiling (C++ projects for instance). Since we have a python environment, I would generally specify the requirements and the installation procedure in the readme.

However, here I have to check if we encounter issues installing on Mac or Windows. If there are some specific operation to be conducted, perhaps adding bash scripts for each OS would be necessary. 

So, if you want, I can handle the multiple-OS build (since it's CI-related) and report here if there are issues, and then you all can decide what you think is best :)

**Comment by chloeskt** [comment]
Hello all! 

As I have less experience than you both, I cannot say what's best. I feel that a exhaustive readme should be sufficient, but again I have less experience right now. 

However I think it's a good idea to make sure that the package builds on all OS, so we should definitely check that out!

**Comment by dataJSA** [comment]
Hello all, 

Thanks a lot @miltminz for your proposal ! 

Concerning the project description I think you are right it would be great to update at least the readme file. 
A contributing file would also be a nice to have it could make the repository a little bit more welcoming 😅 

For the makefile and the scripts I don't know if they are needed yet.

If it is ok for you, I can make a draft of the doc and you will let me know what you think !

**Comment by frgfm** [comment]
I just opened #15 for multiple OS build and will take care of it!
Let me know if you need something else for the incoming release!

**Comment by frgfm** [comment]
Just checking: is this still relevant? considering the already covered installation options

**Comment by dataJSA** [comment]
Yes I agree I think we have covered most points, I will close it !
