### ISSUE TITLE
[test] Unittests need to be optimized for faster execution

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-risks#26]
Since #25, several datasets are not fetched directly from their source APIs. However, the corresponding unittests increased the CI check duration to more than 20minutes, which is too much.

Here is a suggestion on how to proceed:
- [x] Locally add timers in the different unittests to identify bottlenecks
- [ ] Either simplify or regroup some unittests to reduce overhead
- [ ] Potentially avoid redownloading many times using a cache #21 ?

cc @miltminz @chloeskt @dataJSA @GHCamille

**Comment by frgfm** [comment]
Part of the problem could be solved using parallel API requests for the data sources!
But pure inference is still quite long unfortunately

**Comment by frgfm** [comment]
@chloeskt could you report your findings about latency over here please? :pray:

**Comment by frgfm** [comment]
FYI, with #29, the webserver route latency would decrease from 6min30sec to 4min20sec on production servers :ok_hand:

**Comment by chloeskt** [comment]
With the current code in master, I evaluated the running time of the predict pipeline. Here are the results.

for the `get_input` function: 
![image](https://user-images.githubusercontent.com/57073096/102240139-d2d5c000-3ef7-11eb-9b59-de349a03a769.png)

for the `predict` function:
![image](https://user-images.githubusercontent.com/57073096/102240199-dec18200-3ef7-11eb-9401-bc8e06403fa0.png)

Therefore the `get_input` function is the one which takes more time, and more precisely:
- `add_lags` takes 75% of the execution time of the `get_input` function
- `get_fwi_data_for_predict` takes 24.5% of the execution time of the `get_input` function

**Comment by chloeskt** [comment]
Current situation after #29 

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/57073096/102332153-03ffd000-3f8c-11eb-88b0-ac3999ea27b3.png">

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/57073096/102332163-06622a00-3f8c-11eb-83a1-f810f4c398c7.png">

<img width="751" alt="image" src="https://user-images.githubusercontent.com/57073096/102332175-08c48400-3f8c-11eb-91f8-e31a8e7dd0bc.png">

**Comment by frgfm** [comment]
Alright, let's dive into this and figure the current state of this. Can someone run the profiler to identify current bottlenecks please? :pray:

**Comment by dataJSA** [comment]
I am guilty of avoiding this not so sexy issue,  if nobody wants to go ahead with it. I will do it just after solving #36

**Comment by GHCamille** [comment]
I can take care of it @dataJSA ! I think I'll have some time over the weekend 🙃

**Comment by GHCamille** [comment]
Ok so full study with the profiler being done, I identified functions and % of time they take :
![](https://user-images.githubusercontent.com/33114679/108956825-a87b4e00-7670-11eb-9cee-045980176c6a.png)

Then the functions on which we can try to take actions : 

![](https://user-images.githubusercontent.com/33114679/108957001-f8f2ab80-7670-11eb-9ea9-e1c9fe22cfef.png)

I've tried a few tricks on the sjoin but it didn't speed up time. I remember we talked about using shapely and that it was faster ? I'll try to use shapely in an apply tonight, but I'm not so sure it will speed up the process.

For the add_lags function, as @chloeskt said in #28 , the speed problem is really from how the function is built in itself. I'll check what can be done to refactor it in order to speed it up. I guess it will impact other functions around as well.

**Comment by dataJSA** [comment]
@GHCamille, It is awesome thanks for looking this up and logging everything ! 

Concerning the different improvements, I think we can take the two paths:
- Optimize and speedup the different functions that we implemented
- Refactoring and cleaning up the unittest that have been implemented so far 

I look up a bit what could be done for speeding up all the different pandas operations we do. After checking if it's fits our needs we could go with [modin](https://modin.readthedocs.io/en/latest/) it distributes all the pandas builtin operations. I doubt that it would speedup the GitHub actions if they run on single vcpu, but it could be useful overall ! 

For speeding up the unittest as @frgfm suggested we could simplify or regroup some unittests to reduce overhead. 
I checked up what we could try do to do,  I think that  we could:
- Reduce the scope of some unit tests to avoid the downloading using the `patch` module from `unittest.mock` (some functions are already patched, [here is a great introduction to mocking with unittest](https://www.toptal.com/python/an-introduction-to-mocking-in-python))
- Group the downloading steps in set_up class method (I found an example [here](https://stackoverflow.com/questions/8389639/unittest-setup-teardown-for-several-tests)) 

Let me know what you think !

**Comment by GHCamille** [comment]
Thank you for all these insights and documentation ! 😄 

**For the refactoring :**

 - This is very interesting, I didn't know modin. I've tried all I could think of in term of parameter tuning/vectorizing to speedup Geopandas/Shapely operations, and the timing was always about the same. Apparently it doesn't work with Geopandas, but we can still try a bit of tuning.
 - Good news, it seems to work with .shift , meaning that we can use modin for the add_lags function ! On the same subject, I'll try a refactoring of the add_lags function, I have a few ideas. 


**For the unittests :** 

 - Ok I'm looking up this intro link, thanks
 - Grouping the downloading is indeed necessary.

**Comment by GHCamille** [comment]
Insights on what's been done so far: 

**For the refactoring :**

 - On the datasets dowload : I've tried the most basic simplifications like downloading all info at once (CDS api is called several times for the same dataset), and tried building the dataset without the shift() function in the add_lags. Conclusion : it actually adds time. Lot of work, for poor result. 
 - On the Geopandas sjoins : simple loc with a min and max on latitude longitude to focus on the country being 

**Next steps :**

 - Try to use modin on the .shift function, since it doesn't work on the rest of the preparation (not compatible with Geopandas)

**For the unittests :** 

- I've read your articles, but I haven't tried anything yet !

**Comment by dataJSA** [comment]
Thanks for the update on the refactoring @GHCamille ! 

We will see how much performance improvement we can get, even if we only reduce unit tests running time it would be a great progress 😃

**Comment by GHCamille** [comment]
My next step is to work on the unittests, based on your suggestions and articles @dataJSA.

**Comment by dataJSA** [comment]
That's a lot of work and your update was super clear, thanks @GHCamille! 

Unfortunately, the incompatibility with GeoPandas and the differences between the Pandas and Modin API kills all the speed gains that come from using it.

I think we can drop Modin, let me know what you think
