### ISSUE TITLE
Formatting: black ? 

### ISSUE THREAD

**Issue by chloeskt** [pyronear/pyro-risks#8]
This issue regards the formatting of the source code for this repository. I've been using `black` for a while and find it really useful and I believe it helps write cleaner code. However we should agree on what type of formatting we want, and whether we'd like to use `black`.

For more information on black, you can check out the [documentation](https://pypi.org/project/black/) or the [source code](https://github.com/psf/black).

What do you guys think about using a formatter ? Do you agree or not ? Would you like to use another formatter ? Use no formatter ?

**Comment by frgfm** [comment]
cc @GHCamille @dataJSA @miltminz

**Comment by miltminz** [comment]
I definitely agree with the use of a formatter. I'm actually using autopep8 by default on my IDE, but we can integrate black and format everything once the project is a bit more mature?

**Comment by dataJSA** [comment]
I definitely think a code formatter can help a lot, so count me in ! 

I guess the selling point of black is that with its strict conventions it reduces time spent correcting syntax or style error all that  with no configuration, which is great. However, I feel like it reduces a bit code readability. 

By default autopep8 is not as strict as the conventions we enforce now but I think it can be configured with `.flake8` repository file, so we would need to look into it .As @miltminz just said it could be interesting to enforce formatting once the project is a bit more mature. We just have to take a look at the main different tools yapf, autopep8, black,...

**Comment by GHCamille** [comment]
Yep I've been thinking about giving it a try when I get the chance !

**Comment by chloeskt** [comment]
Hi @dataJSA, what do you mean by "However, I feel like it reduces a bit code readability.", because it think that it increases code readability ?

**Comment by dataJSA** [comment]
Hi @chloeskt, 

To clarify, I don't think that using black would make our codebase more readable than it is now, since flake8 as a part of the CI enforces PEP8. However, I do agree that black would ease our workflow (as any other code formatter would) by automating the code formatting.

To make sure that I am clear, black is both a code formatter and a style guide. Thus it not only ensures PEP8 conformity and codebase consistency but also comes with other rules. 

I am not convinced that black code style is more readable than PEP8. However, If you prefer the specific style choices enforced by black over PEP8, that is totally fine by me 🙂

**Comment by chloeskt** [comment]
Closing this issue due to #32
